version: '3.9'
services:
  app:
    image: bitnami/laravel:latest
    volumes:
      - ./source:/app

  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: bookstore
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true

volumes:
  dbdata: